apiVersion: v1
kind: Service
metadata:
  name: kube-tp1-app-service
  labels:
    app: kube-tp1
    component: backend
    resource: app
spec:
  selector:
    app: kube-tp1
    component: backend
    resource: app
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
