apiVersion: v1
kind: Service
metadata:
  name: kube-tp1-front-nginx-service
  labels:
    app: kube-tp1
    component: frontend
    resource: nginx
spec:
  selector:
    app: kube-tp1
    component: frontend
    resource: nginx
  ports:
    - port: 8085
      targetPort: 81
  type: LoadBalancer
