services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - PORT=3000
    working_dir: /app

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8085:80"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - app
    environment:
      - NGINX_PORT=80
      - PROXY_URL=http://app:3000
