FROM node:alpine3.21

RUN apk add --no-cache \
    nginx \ 
    envsubst

WORKDIR /app

COPY docker/nginx/nginx.conf /etc/nginx/http.d/default.conf.template

COPY package.json ./

COPY package-lock.json ./

RUN npm install

COPY . .

COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]

CMD ["nginx", "-g", "daemon off;"]